@server = http://localhost:8080
# @server = http://127.0.0.1:8080

### Long Polling


GET {{server}}/subscribe/john
Content-Type: application/json

###

GET {{server}}/poll/john
Content-Type: application/json

###

POST {{server}}/publish/john
Content-Type: application/json

{
    "message": "Hello, world!"
}